import React, { useState } from 'react';
import { supabase } from '../../../supabase';
import { Printer, FileText, FileBarChart } from 'lucide-react';
import DataCard from '../../DataCard';

const cardStyle = { backgroundColor: 'white', padding: '1.5rem', borderRadius: '12px', boxShadow: '0 2px 10px rgba(0,0,0,0.03)' };

export const ReportModule = ({ report_logs, printSalesTable, printCustomersTable }) => {
  return (
    <div style={cardStyle}>
      <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: '1.5rem', flexWrap: 'wrap', gap: '1rem' }}>
        <h2 style={{ fontSize: '1.25rem', margin: 0 }}>Reports & Analytics</h2>
      </div>
      
      <div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fit, minmax(200px, 1fr))', gap: '1rem', marginBottom: '2rem' }}>
         <div style={{ padding: '1.5rem', border: '1px solid #cbd5e1', borderRadius: '8px', textAlign: 'center' }}>
            <FileText size={32} color="#3b82f6" style={{ marginBottom: '0.5rem' }} />
            <h3 style={{ margin: '0 0 0.5rem 0', fontSize: '1rem' }}>Sales Report</h3>
            <p style={{ fontSize: '0.8rem', color: '#64748b', marginBottom: '1rem' }}>Generate PDF of all sales</p>
            <button onClick={printSalesTable} style={{ width: '100%', padding: '0.5rem', background: '#f1f5f9', color: '#0f172a', border: '1px solid #cbd5e1', borderRadius: '4px', cursor: 'pointer', fontWeight: 'bold' }}>Generate</button>
         </div>
         <div style={{ padding: '1.5rem', border: '1px solid #cbd5e1', borderRadius: '8px', textAlign: 'center' }}>
            <FileText size={32} color="#10b981" style={{ marginBottom: '0.5rem' }} />
            <h3 style={{ margin: '0 0 0.5rem 0', fontSize: '1rem' }}>Customer Report</h3>
            <p style={{ fontSize: '0.8rem', color: '#64748b', marginBottom: '1rem' }}>Generate PDF of all customers</p>
            <button onClick={printCustomersTable} style={{ width: '100%', padding: '0.5rem', background: '#f1f5f9', color: '#0f172a', border: '1px solid #cbd5e1', borderRadius: '4px', cursor: 'pointer', fontWeight: 'bold' }}>Generate</button>
         </div>
      </div>

      <h3 style={{ fontSize: '1.1rem', marginBottom: '1rem' }}>Generated Report Logs</h3>
      
      <div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fill, minmax(300px, 1fr))', gap: '1.25rem' }}>
        {report_logs.map((r, idx) => (
          <DataCard
            key={r.log_id}
            index={idx}
            icon={FileBarChart}
            iconColor="#6366f1"
            title={r.report_title}
            subtitle={`Log: ${r.report_no}`}
            details={[
              { label: 'Generated By', value: r.generated_by || 'System' },
              { label: 'Timestamp', value: new Date(r.generated_at).toLocaleString() }
            ]}
          />
        ))}
      </div>
      {report_logs.length === 0 && <p style={{ padding: '1rem', color: '#64748b' }}>No reports have been generated yet.</p>}
    </div>
  );
};
