import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';
import { Share } from '@capacitor/share';
import { Filesystem, Directory } from '@capacitor/filesystem';

// Helper to get company logo as data URL
export const getWatermarkLogo = async () => {
  try {
    const res = await fetch('/logo.png');
    if (!res.ok) return null;
    const blob = await res.blob();
    return new Promise((resolve) => {
      const reader = new FileReader();
      reader.onloadend = () => resolve(reader.result);
      reader.readAsDataURL(blob);
    });
  } catch (e) {
    console.warn("Could not load logo:", e);
    return null;
  }
};

// Helper to save or share PDF safely across Web and Native mobile (Android/iOS)
export const saveOrSharePDF = async (doc, fileName, isReactPdfBlob = false) => {
  try {
    // Sanitize fileName to prevent path traversal / illegal characters
    const safeFileName = String(fileName || 'document.pdf').replace(/[\/\\?%*:|"<>]/g, '_');

    let pdfBase64 = null;
    if (isReactPdfBlob) {
      // doc is a Blob
      pdfBase64 = await new Promise((resolve) => {
        const reader = new FileReader();
        reader.onloadend = () => resolve(reader.result.split(',')[1]);
        reader.readAsDataURL(doc);
      });
    } else {
      // doc is jsPDF instance
      pdfBase64 = doc.output('datauristring').split(',')[1];
    }

    if (window.Capacitor && window.Capacitor.isNativePlatform()) {
      const savedFile = await Filesystem.writeFile({
        path: safeFileName,
        data: pdfBase64,
        directory: Directory.Cache,
      });
      await Share.share({
        title: `Share ${safeFileName}`,
        url: savedFile.uri,
      });
    } else {
      if (isReactPdfBlob) {
        const url = URL.createObjectURL(doc);
        const a = document.createElement('a');
        a.href = url;
        a.download = safeFileName;
        a.click();
        URL.revokeObjectURL(url);
      } else {
        doc.save(safeFileName);
      }
    }
  } catch (error) {
    console.error("Error saving PDF: ", error);
    alert("Could not generate PDF. Check console.");
  }
};

// 1. Generic Table / Collective Report
export const generateCollectiveReportPDF = async (title, tableColumn, tableRows) => {
  const doc = new jsPDF('landscape');
  const pageWidth = doc.internal.pageSize.getWidth();
  const pageHeight = doc.internal.pageSize.getHeight();

  // Header Logo (Top Right) - maintaining 300x107 aspect ratio (2.8:1)
  const logoBase64 = await getWatermarkLogo();
  if (logoBase64) {
    try {
      doc.addImage(logoBase64, 'PNG', pageWidth - 48, 12, 34, 12.1);
    } catch (e) {
      console.warn("Logo skipped:", e);
    }
  }

  // Header Title
  doc.setFontSize(18);
  doc.setFont("helvetica", "bold");
  doc.setTextColor(0, 51, 102);
  doc.text("AADITYA INDUSTRIES", 14, 18);

  doc.setFontSize(9);
  doc.setFont("helvetica", "normal");
  doc.setTextColor(71, 85, 105);
  doc.text("DEVI STHAN, LOHANIPUR-3, PATNA, BIHAR - 800003", 14, 24);
  doc.text("GSTIN: 10ENXPD2245A1ZL | info@aadityaindustries.com | +91-6202759310", 14, 29);

  doc.setLineWidth(0.5);
  doc.setDrawColor(203, 213, 225);
  doc.line(14, 33, pageWidth - 14, 33);

  // Title
  doc.setFontSize(13);
  doc.setFont("helvetica", "bold");
  doc.setTextColor(15, 23, 42);
  doc.text(String(title || 'REPORT').toUpperCase(), pageWidth / 2, 41, { align: "center" });

  // Info Row
  doc.setFontSize(9);
  doc.setFont("helvetica", "normal");
  doc.setTextColor(100, 116, 139);
  doc.text(`Report Ref: REP${Date.now().toString().slice(-6)}`, 14, 47);
  doc.text(`Generated: ${new Date().toLocaleString('en-IN')}`, pageWidth - 14, 47, { align: "right" });

  doc.setLineWidth(0.2);
  doc.line(14, 50, pageWidth - 14, 50);

  // Table with Page Numbering on every page
  autoTable(doc, {
    head: [tableColumn],
    body: tableRows,
    startY: 54,
    styles: { fontSize: 9, font: "helvetica" },
    headStyles: { fillColor: [241, 245, 249], textColor: [15, 23, 42], fontStyle: 'bold' },
    alternateRowStyles: { fillColor: [255, 255, 255] },
    theme: 'grid',
    didDrawPage: (data) => {
      doc.setFontSize(8);
      doc.setFont("helvetica", "italic");
      doc.setTextColor(148, 163, 184);
      doc.text("Generated by Aaditya Industries ERP", 14, pageHeight - 8);
      doc.text(`Page ${data.pageNumber}`, pageWidth - 14, pageHeight - 8, { align: 'right' });
    }
  });

  const safeTitle = String(title || 'Report').replace(/[\/\\?%*:|"<>]/g, '_').replace(/\s+/g, '_');
  const fileName = `${safeTitle}_${Date.now()}.pdf`;
  saveOrSharePDF(doc, fileName);
};

// 2. Individual Invoice / Quotation / Purchase Note
export const generateIndividualInvoicePDF = async (type, data, items = [], isQuotation = false, payments = []) => {
  const doc = new jsPDF();
  const pageWidth = doc.internal.pageSize.getWidth();
  const pageHeight = doc.internal.pageSize.getHeight();

  // Header Logo (Top Right) - strictly preserving 300x107 aspect ratio (2.8:1)
  const logoBase64 = await getWatermarkLogo();
  if (logoBase64) {
    try {
      doc.addImage(logoBase64, 'PNG', pageWidth - 50, 12, 36, 12.8);
    } catch (e) {
      console.warn("Header logo skipped:", e);
    }
  }

  // Company Details Header (Top Left)
  doc.setFontSize(17);
  doc.setFont("helvetica", "bold");
  doc.setTextColor(0, 51, 102);
  doc.text("AADITYA INDUSTRIES", 14, 18);

  doc.setFontSize(9);
  doc.setFont("helvetica", "normal");
  doc.setTextColor(71, 85, 105);
  doc.text("Devi Sthan, Lohanipur-3, Patna, Bihar - 800003", 14, 24);
  doc.text("GSTIN: 10ENXPD2245A1ZL | Adityamohan425@gmail.com| +91-6202759310", 14, 29);

  doc.setLineWidth(0.8);
  doc.setDrawColor(203, 213, 225);
  doc.line(14, 34, pageWidth - 14, 34);

  // Title
  doc.setFontSize(13);
  doc.setFont("helvetica", "bold");
  doc.setTextColor(15, 23, 42);
  const title = isQuotation ? "QUOTATION" : (type === 'sale' ? "TAX INVOICE" : "PURCHASE NOTE");
  doc.text(title, pageWidth / 2, 42, { align: "center" });

  // Two Column Info Block
  doc.setFontSize(9);
  const formatVal = (val) => (val && String(val).trim() !== '' && val !== 'null' && val !== 'undefined') ? String(val).trim() : 'N/A';

  if (type === 'sale') {
    // Bill To
    doc.setFont("helvetica", "bold");
    doc.setTextColor(15, 23, 42);
    doc.text(isQuotation ? "QUOTE TO:" : "BILL TO:", 14, 50);
    doc.setFont("helvetica", "normal");
    doc.setTextColor(51, 65, 85);
    doc.text(`Name: ${formatVal(data.customer_name || data.name)}`, 14, 55);
    doc.text(`Phone: ${formatVal(data.customer_phone || data.cust_comp_person_no || data.cust_comp_no)}`, 14, 60);
    doc.text(`Email: ${formatVal(data.customer_email || data.cust_email)}`, 14, 65);

    let rawAddr = data.customer_address || data.cust_address || '';
    let addr = rawAddr && rawAddr !== 'null' && rawAddr !== 'undefined' ? rawAddr.substring(0, 45) : 'N/A';
    doc.text(`Address: ${addr}`, 14, 70);
    if (!isQuotation) {
      doc.text(`GSTIN: ${formatVal(data.customer_gst_no || data.customer_gstno || data.cust_gst_no)}`, 14, 75);
    }

    // Invoice Details
    doc.setFont("helvetica", "bold");
    doc.setTextColor(15, 23, 42);
    doc.text(isQuotation ? "QUOTE DETAILS:" : "INVOICE DETAILS:", pageWidth / 2, 50);
    doc.setFont("helvetica", "normal");
    doc.setTextColor(51, 65, 85);
    doc.text(`${isQuotation ? 'Quote Ref' : 'Invoice No'}: ${data.id || data.invoice_no || `QT-${Date.now().toString().slice(-6)}`}`, pageWidth / 2, 55);
    doc.text(`Date: ${(data.sale_date || data.created_at || new Date().toISOString()).split('T')[0]}`, pageWidth / 2, 60);
    if (!isQuotation) {
      doc.text(`Delivery Date: ${data.delivery_date ? data.delivery_date.split('T')[0] : 'N/A'}`, pageWidth / 2, 65);
      doc.text(`Payment: ${data.payment_status || 'N/A'} (${data.payment_method || 'N/A'})`, pageWidth / 2, 70);
      doc.text(`Order Status: ${data.order_status || 'Delivered'}`, pageWidth / 2, 75);
    } else {
      doc.text("Validity: 30 Days from date of issue", pageWidth / 2, 65);
    }
  } else {
    // Supplier Block
    doc.setFont("helvetica", "bold");
    doc.setTextColor(15, 23, 42);
    doc.text("SUPPLIER DETAILS:", 14, 50);
    doc.setFont("helvetica", "normal");
    doc.setTextColor(51, 65, 85);
    const suppName = formatVal(data.vendor_name || data.supplier_name || data.supp_comp_name || data.supplier_id);
    doc.text(`Supplier: ${suppName}`, 14, 55);
    doc.text(`Phone: ${formatVal(data.supplier_phone || data.supp_comp_no)}`, 14, 60);
    doc.text(`GSTIN: ${formatVal(data.supplier_gst_no || data.supp_gst_no)}`, 14, 65);

    // Purchase Order Details
    doc.setFont("helvetica", "bold");
    doc.setTextColor(15, 23, 42);
    doc.text("PURCHASE ORDER DETAILS:", pageWidth / 2, 50);
    doc.setFont("helvetica", "normal");
    doc.setTextColor(51, 65, 85);
    doc.text(`PO Number: ${data.id || data.purchase_id}`, pageWidth / 2, 55);
    doc.text(`Date: ${(data.purchase_date || data.created_at || new Date().toISOString()).split('T')[0]}`, pageWidth / 2, 60);
    doc.text(`Status: ${data.payment_status || data.order_status || 'Completed'}`, pageWidth / 2, 65);
    doc.text(`Payment Mode: ${data.payment_method || 'Cash'}`, pageWidth / 2, 70);
  }

  // Items Table (Use standard Rs. to prevent jsPDF Unicode font corruption)
  const tableColumn = ["#", "Product Description", "HSN", "Qty", "Rate (Rs.)", "Total (Rs.)"];
  const tableRows = (items || []).map((item, index) => {
    const qty = Number(item.quantity ?? 1);
    const rate = Number(item.unit_price || item.unit_cost || 0);
    const lineTotal = Number(item.total_price || item.total_cost || (qty * rate) + Number(item.tax_amount || 0));
    return [
      (index + 1).toString(),
      item.product_name || item.product_id || 'Product',
      item.hsn_code || '—',
      qty.toString(),
      rate.toFixed(2),
      lineTotal.toFixed(2)
    ];
  });

  autoTable(doc, {
    head: [tableColumn],
    body: tableRows,
    startY: 82,
    styles: { fontSize: 9, font: "helvetica" },
    headStyles: { fillColor: [241, 245, 249], textColor: [15, 23, 42], fontStyle: 'bold' },
    alternateRowStyles: { fillColor: [255, 255, 255] },
    theme: 'grid'
  });

  // Summary Block
  let currentY = (doc.lastAutoTable.finalY || 82) + 8;

  // Protect against summary block spilling off page bottom
  if (currentY > pageHeight - 65) {
    doc.addPage();
    currentY = 20;
  }

  const rightColX = pageWidth - 14;
  const labelColX = pageWidth - 70;

  const addRow = (label, value, isBold = false) => {
    doc.setFont("helvetica", isBold ? "bold" : "normal");
    doc.text(label, labelColX, currentY);
    doc.text(value, rightColX, currentY, { align: "right" });
    currentY += 5;
  };

  doc.setFontSize(9);
  addRow("Sub Total:", `Rs. ${Number(data.total_amount || 0).toFixed(2)}`);
  if (Number(data.discount || 0) > 0) addRow("Discount:", `-Rs. ${Number(data.discount).toFixed(2)}`);
  if (Number(data.tax_total || data.tax || 0) > 0) addRow("Tax:", `Rs. ${Number(data.tax_total || data.tax).toFixed(2)}`);
  if (Number(data.transport || 0) > 0) addRow("Transport:", `Rs. ${Number(data.transport).toFixed(2)}`);

  currentY += 1;
  doc.setFontSize(10.5);
  doc.setTextColor(0, 51, 102);
  addRow("Grand Total:", `Rs. ${Number(data.grand_total || 0).toFixed(2)}`, true);

  doc.setFontSize(9);
  doc.setTextColor(0, 0, 0);

  const grandTotal = Number(data.grand_total || 0);
  const initialAdvance = Number(data.advance_amount || 0);
  const totalPaid = Number(data.amount_paid !== undefined && data.amount_paid !== null ? data.amount_paid : initialAdvance);
  const due = Math.max(0, Number(data.dues !== undefined ? data.dues : (grandTotal - totalPaid)));
  const isFullyPaid = due <= 0.01;

  if (initialAdvance > 0) {
    currentY += 1;
    addRow("Advance Paid:", `Rs. ${initialAdvance.toFixed(2)}`);
  }

  if (totalPaid > initialAdvance) {
    addRow("Total Amount Paid:", `Rs. ${totalPaid.toFixed(2)}`);
  }

  if (isFullyPaid) {
    currentY += 2;
    doc.setTextColor(16, 185, 129); // Green
    addRow("Payment Status:", "PAYMENT DONE (CLEARED)", true);
    doc.setTextColor(0, 0, 0);
  } else {
    currentY += 2;
    doc.setTextColor(220, 38, 38); // Red
    addRow("Balance Due:", `Rs. ${due.toFixed(2)}`, true);
    doc.setTextColor(0, 0, 0);
  }

  // Build Comprehensive Payment Ledger (including Initial Advance + All Subsequent Receipts)
  const fullPaymentLedger = [];
  const invoiceDate = (data.sale_date || data.purchase_date || data.created_at || new Date().toISOString()).split('T')[0];

  if (initialAdvance > 0) {
    fullPaymentLedger.push({
      date: invoiceDate,
      description: 'Initial Advance (at Invoice Creation)',
      mode: data.payment_method || 'Cash',
      amount: initialAdvance,
      isExpense: false
    });
  }

  (payments || []).forEach(p => {
    // Avoid duplicate if payment was already recorded with same advance description
    const isExpense = p.transaction_type === 'Expense';
    fullPaymentLedger.push({
      date: (p.payment_date || p.transaction_date || p.created_at || '').split('T')[0],
      description: p.description || `Payment against ${data.id}`,
      mode: p.account_type || p.payment_method || 'Cash',
      amount: Number(p.amount || 0),
      isExpense
    });
  });

  // Render Payment Receipt Ledger Table if any advance or payments exist
  if (fullPaymentLedger.length > 0) {
    currentY += 6;
    if (currentY > pageHeight - 55) {
      doc.addPage();
      currentY = 20;
    }

    doc.setFontSize(9.5);
    doc.setFont("helvetica", "bold");
    doc.setTextColor(15, 23, 42);
    doc.text("PAYMENT RECEIPT HISTORY", 14, currentY);

    const paymentRows = fullPaymentLedger.map((p, idx) => {
      const sign = p.isExpense ? '- Rs. ' : 'Rs. ';
      return [
        (idx + 1).toString(),
        p.date,
        p.description,
        p.mode,
        `${sign}${p.amount.toFixed(2)}`
      ];
    });

    autoTable(doc, {
      head: [["#", "Date", "Payment Description", "Mode", "Amount (Rs.)"]],
      body: paymentRows,
      startY: currentY + 3,
      styles: { fontSize: 8.5, font: "helvetica" },
      headStyles: { fillColor: [241, 245, 249], textColor: [15, 23, 42], fontStyle: 'bold' },
      alternateRowStyles: { fillColor: [255, 255, 255] },
      theme: 'grid'
    });

    currentY = (doc.lastAutoTable.finalY || currentY) + 8;
  }

  // Terms & Conditions and Signature (Footer)
  if (currentY > pageHeight - 45) {
    doc.addPage();
    currentY = 20;
  }

  doc.setFontSize(8);
  doc.setFont("helvetica", "italic");
  doc.setTextColor(100, 116, 139);
  doc.text("Terms & Conditions:\n1. Goods once sold will not be taken back.\n2. Warranty as per manufacturer terms.\n3. Subject to Patna Jurisdiction only.", 14, currentY);

  currentY += 15;
  doc.setLineWidth(0.2);
  doc.setDrawColor(203, 213, 225);
  doc.line(14, currentY, pageWidth - 14, currentY);

  currentY += 6;
  doc.text("Generated by Aaditya Industries ERP", 14, currentY);
  doc.setFont("helvetica", "bold");
  doc.setTextColor(15, 23, 42);
  doc.text("__________________________\nAuthorized Signatory", pageWidth - 14, currentY, { align: "right" });

  const safeId = String(data.id || 'Invoice').replace(/[\/\\?%*:|"<>]/g, '_');
  const fileName = `${safeId}_${Date.now()}.pdf`;
  saveOrSharePDF(doc, fileName);
};
