import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';
import { Share } from '@capacitor/share';
import { Filesystem, Directory } from '@capacitor/filesystem';

// Helper to save or share PDF
// Helper to save or share PDF
export const getWatermarkLogo = async () => {
  try {
    const res = await fetch('/logo.png');
    const blob = await res.blob();
    return new Promise((resolve) => {
      const reader = new FileReader();
      reader.onloadend = () => resolve(reader.result);
      reader.readAsDataURL(blob);
    });
  } catch (e) {
    console.error("Could not load watermark logo", e);
    return null;
  }
};

export const saveOrSharePDF = async (doc, fileName, isReactPdfBlob = false) => {
  try {
    let pdfBase64 = null;
    if (isReactPdfBlob) {
      // doc is a Blob
      pdfBase64 = await new Promise((resolve) => {
        const reader = new FileReader();
        reader.onloadend = () => resolve(reader.result.split(',')[1]);
        reader.readAsDataURL(doc);
      });
    } else {
      // doc is jsPDF instance
      pdfBase64 = doc.output('datauristring').split(',')[1];
    }

    if (window.Capacitor && window.Capacitor.isNativePlatform()) {
      const savedFile = await Filesystem.writeFile({
        path: fileName,
        data: pdfBase64,
        directory: Directory.Cache,
      });
      await Share.share({
        title: `Share ${fileName}`,
        url: savedFile.uri,
      });
    } else {
      if (isReactPdfBlob) {
        const url = URL.createObjectURL(doc);
        const a = document.createElement('a');
        a.href = url;
        a.download = fileName;
        a.click();
        URL.revokeObjectURL(url);
      } else {
        doc.save(fileName);
      }
    }
  } catch (error) {
    console.error("Error saving PDF: ", error);
    alert("Could not generate PDF. Check console.");
  }
};

// 1. Generic Table / Collective Report
export const generateCollectiveReportPDF = async (title, tableColumn, tableRows) => {
  const doc = new jsPDF('landscape');

  // Header
  doc.setFontSize(18);
  doc.setFont("helvetica", "bold");
  doc.setTextColor(0, 51, 102);
  doc.text("AADITYA INDUSTRIES", doc.internal.pageSize.getWidth() / 2, 20, { align: "center" });

  doc.setFontSize(10);
  doc.setFont("helvetica", "normal");
  doc.setTextColor(0, 0, 0);
  doc.text("DEVI STHAN, LOHANIPUR-3", doc.internal.pageSize.getWidth() / 2, 26, { align: "center" });
  doc.text("GST: 10ENXPD2245A1ZL", doc.internal.pageSize.getWidth() / 2, 31, { align: "center" });
  doc.text("info@aadityaindustries.com | +91-9835660992", doc.internal.pageSize.getWidth() / 2, 36, { align: "center" });

  doc.setLineWidth(0.5);
  doc.line(14, 40, doc.internal.pageSize.getWidth() - 14, 40);

  // Title
  doc.setFontSize(12);
  doc.setFont("helvetica", "bold");
  doc.text(title.toUpperCase(), doc.internal.pageSize.getWidth() / 2, 48, { align: "center" });

  // Watermark
  const logoBase64 = await getWatermarkLogo();
  if (logoBase64) {
    doc.setGState(new doc.GState({ opacity: 0.15 }));
    const w = 100;
    const h = 100;
    const x = (doc.internal.pageSize.getWidth() - w) / 2;
    const y = (doc.internal.pageSize.getHeight() - h) / 2;
    doc.addImage(logoBase64, 'PNG', x, y, w, h);
    doc.setGState(new doc.GState({ opacity: 1.0 }));
  }

  // Info Row
  doc.setFontSize(9);
  doc.setFont("helvetica", "normal");
  doc.text(`Report No: REP${Date.now().toString().slice(-6)}`, 14, 55);
  doc.text(`Date: ${new Date().toLocaleString()}`, doc.internal.pageSize.getWidth() - 14, 55, { align: "right" });

  doc.setLineWidth(0.2);
  doc.line(14, 58, doc.internal.pageSize.getWidth() - 14, 58);

  // Table
  autoTable(doc, {
    head: [tableColumn],
    body: tableRows,
    startY: 65,
    styles: { fontSize: 9, font: "helvetica" },
    headStyles: { fillColor: [230, 230, 230], textColor: [0, 0, 0], fontStyle: 'bold' },
    alternateRowStyles: { fillColor: [255, 255, 255] }
  });

  // Footer
  const finalY = doc.lastAutoTable.finalY || 65;
  if (finalY < doc.internal.pageSize.getHeight() - 30) {
    doc.setFontSize(8);
    doc.setFont("helvetica", "italic");
    doc.text("Generated by AADITYA INDUSTRIES", 14, doc.internal.pageSize.getHeight() - 10);
  }

  const fileName = `${title.replace(/\s+/g, '_')}_${Date.now()}.pdf`;
  saveOrSharePDF(doc, fileName);
};

// 2. Individual Invoice
export const generateIndividualInvoicePDF = async (type, data, items) => {
  const doc = new jsPDF();

  // Header
  doc.setFontSize(18);
  doc.setFont("helvetica", "bold");
  doc.setTextColor(0, 51, 102);
  doc.text("AADITYA INDUSTRIES", 14, 20);

  doc.setFontSize(10);
  doc.setFont("helvetica", "normal");
  doc.setTextColor(0, 0, 0);
  doc.text("Devi Sthan, Lohanipur-3, Patna, Bihar", 14, 26);
  doc.text("GSTIN: 10ENXPD2245A1ZL | info@aadityaindustries.com", 14, 31);

  doc.setLineWidth(1.2);
  doc.line(14, 35, doc.internal.pageSize.getWidth() - 14, 35);

  // Title
  doc.setFontSize(14);
  doc.setFont("helvetica", "bold");
  const title = type === 'sale' ? "SALE INVOICE" : "PURCHASE NOTE";
  doc.text(title, doc.internal.pageSize.getWidth() / 2, 45, { align: "center" });

  // Two Column Info
  doc.setFontSize(10);
  const formatVal = (val) => (val && val !== 'null' && val !== 'undefined') ? val : 'N/A';

  if (type === 'sale') {
    doc.setFont("helvetica", "bold");
    doc.text("BILL TO:", 14, 55);
    doc.setFont("helvetica", "normal");
    doc.text(`Name: ${formatVal(data.customer_name)}`, 14, 60);
    doc.text(`Phone: ${formatVal(data.customer_phone)}`, 14, 65);
    doc.text(`Email: ${formatVal(data.customer_email)}`, 14, 70);

    let addr = 'N/A';
    if (data.customer_address && data.customer_address !== 'null' && data.customer_address !== 'undefined') {
      addr = data.customer_address.substring(0, 40);
    }
    doc.text(`Address: ${addr}`, 14, 75);
    doc.text(`GSTIN: ${formatVal(data.customer_gst_no)}`, 14, 80);

    doc.setFont("helvetica", "bold");
    doc.text("INVOICE DETAILS:", doc.internal.pageSize.getWidth() / 2, 55);
    doc.setFont("helvetica", "normal");
    doc.text(`Invoice No: ${data.id}`, doc.internal.pageSize.getWidth() / 2, 60);
    doc.text(`Sale Date: ${data.sale_date ? data.sale_date.split('T')[0] : 'N/A'}`, doc.internal.pageSize.getWidth() / 2, 65);
    doc.text(`Delivery Date: ${data.delivery_date ? data.delivery_date.split('T')[0] : 'N/A'}`, doc.internal.pageSize.getWidth() / 2, 70);
    doc.text(`Payment: ${data.payment_status || 'N/A'} (${data.payment_method || 'N/A'})`, doc.internal.pageSize.getWidth() / 2, 75);
    doc.text(`Status: ${data.order_status || 'N/A'}`, doc.internal.pageSize.getWidth() / 2, 80);
  } else {
    doc.setFont("helvetica", "bold");
    doc.text("SUPPLIER:", 14, 55);
    doc.setFont("helvetica", "normal");
    doc.text(`Name: ${formatVal(data.vendor_name)}`, 14, 60);

    doc.setFont("helvetica", "bold");
    doc.text("INVOICE DETAILS:", doc.internal.pageSize.getWidth() / 2, 55);
    doc.setFont("helvetica", "normal");
    doc.text(`Order ID: ${data.id}`, doc.internal.pageSize.getWidth() / 2, 60);
    doc.text(`Date: ${data.purchase_date ? data.purchase_date.split('T')[0] : 'N/A'}`, doc.internal.pageSize.getWidth() / 2, 65);
  }

  // Items Table
  const tableColumn = ["Sl", "Product Description", "HSN", "Qty", "Rate", "Total"];
  const tableRows = items.map((item, index) => [
    (index + 1).toString(),
    item.product_name,
    item.hsn_code || "",
    item.quantity.toString(),
    Number(item.unit_price || 0).toFixed(2),
    (Number(item.total_price || 0) + Number(item.tax_amount || 0)).toFixed(2)
  ]);

  autoTable(doc, {
    head: [tableColumn],
    body: tableRows,
    startY: 90,
    styles: { fontSize: 9, font: "helvetica" },
    headStyles: { fillColor: [230, 230, 230], textColor: [0, 0, 0], fontStyle: 'bold' },
    alternateRowStyles: { fillColor: [255, 255, 255] }
  });

  // Summary
  let currentY = doc.lastAutoTable.finalY + 10;

  const rightColX = doc.internal.pageSize.getWidth() - 14;
  const labelColX = doc.internal.pageSize.getWidth() - 65;

  const addRow = (label, value, isBold = false) => {
    doc.setFont("helvetica", isBold ? "bold" : "normal");
    doc.text(label, labelColX, currentY);
    doc.text(value, rightColX, currentY, { align: "right" });
    currentY += 5;
  };

  addRow("Sub Total:", Number(data.total_amount || 0).toFixed(2));
  if (data.discount > 0) addRow("Discount:", `-${Number(data.discount).toFixed(2)}`);
  if (data.tax_total > 0) addRow("Total Tax:", Number(data.tax_total).toFixed(2));
  if (data.transport > 0) addRow("Transport:", Number(data.transport).toFixed(2));

  currentY += 2;
  doc.setFontSize(12);
  doc.setTextColor(0, 51, 102);
  addRow("Grand Total:", `Rs ${Number(data.grand_total || 0).toFixed(2)}`, true);

  doc.setFontSize(10);
  doc.setTextColor(0, 0, 0);
  if (data.advance_amount > 0) {
    currentY += 3;
    addRow("Advance Paid:", Number(data.advance_amount).toFixed(2));
    doc.setTextColor(255, 0, 0);
    addRow("Balance Due:", `Rs ${Number(data.dues || 0).toFixed(2)}`, true);
    doc.setTextColor(0, 0, 0);
  }

  // Footer
  currentY += 20;
  if (currentY > doc.internal.pageSize.getHeight() - 30) {
    doc.addPage();
    currentY = 20;
  }

  doc.setFontSize(8);
  doc.setFont("helvetica", "italic");
  doc.text("Terms & Conditions:\n1. Goods once sold will not be taken back.\n2. Warranty as per manufacturer terms.", 14, currentY);

  currentY += 15;
  doc.setLineWidth(0.1);
  doc.line(14, currentY, doc.internal.pageSize.getWidth() - 14, currentY);

  currentY += 5;
  doc.text("Generated by Aaditya Industries", 14, currentY);
  doc.setFont("helvetica", "bold");
  doc.text("__________________________\nAuthorized Signatory", doc.internal.pageSize.getWidth() - 14, currentY, { align: "right" });

  const fileName = `${data.id}_${Date.now()}.pdf`;
  saveOrSharePDF(doc, fileName);
};
